name: config
description: A starting point for Dart libraries or applications.
version: 0.0.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
